### ISSUE TITLE
antixccslim.sh error

### ISSUE THREAD

**Issue by anticapitalista** [antiX-Linux/slim-antix#1]
sudo antixccslim.sh 
[sudo] password for anticap: 
/usr/local/bin/antixccslim.sh: line 13: syntax error near unexpected token `then'
/usr/local/bin/antixccslim.sh: line 13: `if[ ! -w /etc/slim.conf ]; then'

**Comment by antiX-Dave** [comment]
I think it needs a space between the if and [ but I have not tested
